### ISSUE TITLE
Do not ignore src/node_modules in xo and jest.

### ISSUE THREAD

**Issue by reklatsmasters** [reklatsmasters/binary-data#12]

**Comment by FezVrasta** [comment]
Use the `NODE_PATH` environment variable instead of the `node_modules` hack

**Comment by reklatsmasters** [comment]
@FezVrasta `NODE_PATH` variable is a part of old APIs.

> NODE_PATH was originally created to support loading modules from varying paths before the current module resolution algorithm was frozen.

It's not supported by [ESM](https://nodejs.org/dist/latest-v8.x/docs/api/esm.html#esm_no_node_path). Instead, `node_modules` is a key part of nodejs https://github.com/nodejs/node/issues/15755#issuecomment-334078724.

**Comment by FezVrasta** [comment]
`node_modules` is not meant to be used the way you are doing, it's just going to cause problems. Anyway, do was you prefer.

**Comment by reklatsmasters** [comment]
Resolved in 65e2fc5c1034b78651e5a101ae6b365b7e0df5da and a77fd4c347a091ef503c7f81f38fd13e6f17ac78.
